---
title: The QRL Info
email: james@theqrl.org
author: Fr1t2
description: Information on The Quantum Resistant Ledger and Quantum Computer advancement
baseurl:
url: http://theqrl.info
date_format: "%b %-d, %Y"
header_pages:
- links.md
- about.md
- contact.html
google_verification: 
google_analytics: UA-58105019-3
google_tag_manager: 
bing_verification: 
animated: true
show_related_posts: false
show_post_footers: true
show_social_icons: true
ajaxify_contact_form: false
enable_mathjax: true
extended_fonts: true
enable_anchorjs: true
post_preview_image: false
fb_page: false
fb_page_id: 
disqus_shortname: 
txtpen_sitename: 
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10
github_username: theqrl
reddit_username: mc_schmitt
bitbucket_username: 
stackoverflow_id: qrledger
twitter_username: qrledger
skype_username: 
steam_nickname: 
google_plus_id: 
linkedin_username: 
angellist_username: 
medium_id: the-quantum-resistant-ledger
bitcoin_url: 
paypal_url: 
flattr_button: 
telegram_username: 
vk_id: 
show_sharing_icons: true
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: true
text:
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: Email Address
    content: What would you like to say?
    subject: New submission!
    submit: Say Hello
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for contacting us. We will reply as soon as possible.
  og_locale: en_US
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: pretty
paginate: 4
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- vendor
