---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Site Layout
- type: directory
  path: _layouts
  label: _layouts
  create: all
  match: "**/*"
- type: directory
  path: _includes
  label: _Includes
  create: all
  match: "**/*"
- type: heading
  label: Content
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post-temp
  - post
- type: heading
  label: Global
- type: document
  path: thanks.md
  label: thanks.md
- type: document
  path: _config.yml
  label: config
- type: document
  path: contact.html
  label: contact.html
  match: "**/*"
- type: document
  path: README.md
  label: README.md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
