---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Site Layout
- type: directory
  path: _layouts
  label: _layouts
  create: all
  match: "**/*"
- type: directory
  path: _includes
  label: _Includes
  create: all
  match: "**/*"
- type: heading
  label: Content
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Global
- type: document
  path: _config.yml
  label: config
- type: document
  path: CNAME
  label: CNAME
  match: "**/*"
- type: document
  path: feed.xml
  label: feed.xml
  match: "**/*"
- type: document
  path: GEMFILE
  label: GEMFILE
  match: "**/*"
- type: document
  path: Rakefile
  label: Rakefile
  match: "**/*"
- type: document
  path: README.md
  label: README.md
  match: "**/*"
- type: document
  path: fb-instant-articles.xml
  label: fb-instant-articles
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
